version: '3.4'

networks:
  sol:
    driver: bridge 

services:
  sol.identity:
    image: ${DOCKER_REGISTRY-}solidentity
    container_name: identity_api
    depends_on:
      - "identity_db"
    build:
      context: .
      dockerfile: SOL.Identity/Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=identity_db;port=5432;database=identity;username=postgress;password=postgress"
      ASPNETCORE_ENVIRONMENT: Development
    volumes: 
      # for development
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - sol

  identity_db:
    image: postgres:latest
    container_name: identity_db
    ports:
      - "5432"
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgress"
      POSTGRES_PASSWORD: "postgress"
      POSTGRES_DB: "identity"
      PGDATA: /data/postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    networks:
      - sol

  sol.web:
    image: nginx:stable-alpine
    container_name: sol_web
    restart: always
    build:
      context: .
      dockerfile: SOL.Web/Dockerfile
    ports:
      - "8080:80"
    networks:
      - sol

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - sol

volumes:
  db_volume:
